from typing import Literal


# ---------- Entity Types ----------
EntityType = Literal[
    "Person",
    "Organization",
    "Place",
    "AdministrativeTerritory",
    "Location",
    "BodyOfWater",
    "Work",
    "Product",
    "Event",
    "Time",
    "Concept",
    "Class",
    "Taxon",
    "Language",
    "Award",
    "Position",
    "Genre",
    "Religion",
    "EthnicGroup",
    "Conflict",
    "LegalDocument",
    "Other",
]

ENTITY_TYPES_DESC = {
    "Person": "Human individuals (real or fictional).",
    "Organization": "Companies, institutions, parties, teams, agencies, bands, etc.",
    "Place": "Geopolitical entities: countries, states, cities, regions.",
    "AdministrativeTerritory": "Administrative subdivisions (provinces, departments, counties).",
    "Location": "Physical places: buildings, facilities, addresses, terrain features.",
    "BodyOfWater": "Rivers, lakes, seas, oceans, straits.",
    "Work": "Creative works: books, films, albums, songs, TV shows, games, artworks.",
    "Product": "Manufactured products, software, vehicles, devices.",
    "Event": "Discrete happenings with a time/place (excluding wars).",
    "Time": "Dates, years, periods (e.g. '1999-03-12', 'the 1980s').",
    "Concept": "Abstract ideas, theories, disciplines, topics.",
    "Class": "Types/categories used as the object of 'instance of' / 'subclass of'.",
    "Taxon": "Biological taxa (species, genus, family, etc.).",
    "Language": "Natural or constructed languages.",
    "Award": "Prizes, honors, distinctions.",
    "Position": "Job titles, roles, offices held.",
    "Genre": "Artistic, musical, literary, film genres.",
    "Religion": "Religions and denominations.",
    "EthnicGroup": "Ethnic groups and peoples.",
    "Conflict": "Wars, battles, armed conflicts.",
    "LegalDocument": "Laws, treaties, regulations, statutes.",
    "Other": "Use only when no other type fits.",
}
# ---------- Relation Types (mirrors your list exactly) ----------
RelationType = Literal[
    "head of government",
    "country",
    "place of birth",
    "place of death",
    "father",
    "mother",
    "spouse",
    "country of citizenship",
    "continent",
    "instance of",
    "head of state",
    "capital",
    "official language",
    "position held",
    "child",
    "author",
    "member of sports team",
    "director",
    "screenwriter",
    "educated at",
    "composer",
    "member of political party",
    "employer",
    "founded by",
    "league",
    "publisher",
    "owned by",
    "located in the administrative territorial entity",
    "genre",
    "operator",
    "religion",
    "contains administrative territorial entity",
    "follows",
    "followed by",
    "headquarters location",
    "cast member",
    "producer",
    "award received",
    "creator",
    "parent taxon",
    "ethnic group",
    "performer",
    "manufacturer",
    "developer",
    "series",
    "sister city",
    "legislative body",
    "basin country",
    "located in or next to body of water",
    "military branch",
    "record label",
    "production company",
    "location",
    "subclass of",
    "subsidiary",
    "part of",
    "original language of work",
    "platform",
    "mouth of the watercourse",
    "original network",
    "member of",
    "chairperson",
    "country of origin",
    "has part",
    "residence",
    "date of birth",
    "date of death",
    "inception",
    "dissolved, abolished or demolished",
    "publication date",
    "start time",
    "end time",
    "point in time",
    "conflict",
    "characters",
    "lyrics by",
    "located on terrain feature",
    "participant",
    "influenced by",
    "location of formation",
    "parent organization",
    "notable work",
    "separated from",
    "narrative location",
    "work location",
    "applies to jurisdiction",
    "product or material produced",
    "unemployment rate",
    "territory claimed by",
    "participant of",
    "replaces",
    "replaced by",
    "capital of",
    "languages spoken, written or signed",
    "present in work",
    "sibling",
]

# ---------- Domain/Range constraints ----------
# Maps each relation to (allowed subject types, allowed object types).
# Use None to mean "any type".  This is the *contract* the LLM must respect.
RELATION_CONSTRAINTS = {
    "head of government": (["Place", "AdministrativeTerritory"], ["Person"]),
    "head of state": (["Place", "AdministrativeTerritory"], ["Person"]),
    "place of birth": (["Person"], ["Place", "Location"]),
    "place of death": (["Person"], ["Place", "Location"]),
    "father": (["Person"], ["Person"]),
    "mother": (["Person"], ["Person"]),
    "spouse": (["Person"], ["Person"]),
    "child": (["Person"], ["Person"]),
    "sibling": (["Person"], ["Person"]),
    "country of citizenship": (["Person"], ["Place"]),
    "continent": (["Place"], ["Place"]),
    "country": (
        [
            "Place",
            "Location",
            "Organization",
            "Work",
            "Conflict",
            "AdministrativeTerritory",
        ],
        ["Place"],
    ),
    "instance of": (None, ["Class", "Concept"]),
    "capital": (["Place"], ["Place", "Location"]),
    "capital of": (["Place", "Location"], ["Place"]),
    "official language": (["Place"], ["Language"]),
    "position held": (["Person"], ["Position"]),
    "author": (["Work"], ["Person"]),
    "director": (["Work"], ["Person"]),
    "screenwriter": (["Work"], ["Person"]),
    "composer": (["Work"], ["Person"]),
    "lyrics by": (["Work"], ["Person"]),
    "cast member": (["Work"], ["Person"]),
    "performer": (["Work"], ["Person"]),
    "producer": (["Work"], ["Person", "Organization"]),
    "creator": (["Work", "Product"], ["Person", "Organization"]),
    "manufacturer": (["Product"], ["Organization"]),
    "developer": (["Product", "Work"], ["Organization", "Person"]),
    "member of sports team": (["Person"], ["Organization"]),
    "member of political party": (["Person"], ["Organization"]),
    "member of": (["Person", "Organization"], ["Organization"]),
    "employer": (["Person"], ["Organization", "Person"]),
    "chairperson": (["Organization"], ["Person"]),
    "educated at": (["Person"], ["Organization"]),
    "founded by": (["Organization", "Place"], ["Person", "Organization"]),
    "parent organization": (["Organization"], ["Organization"]),
    "subsidiary": (["Organization"], ["Organization"]),
    "headquarters location": (["Organization"], ["Place", "Location"]),
    "league": (["Organization"], ["Organization"]),
    "publisher": (["Work"], ["Organization", "Person"]),
    "production company": (["Work"], ["Organization"]),
    "record label": (["Work"], ["Organization"]),
    "owned by": (["Organization", "Product"], ["Organization", "Person"]),
    "operator": (["Location", "Organization"], ["Organization", "Person"]),
    "located in the administrative territorial entity": (
        ["Place", "Location"],
        ["Place", "AdministrativeTerritory"],
    ),
    "contains administrative territorial entity": (
        ["Place", "AdministrativeTerritory"],
        ["Place", "AdministrativeTerritory"],
    ),
    "sister city": (["Place"], ["Place"]),
    "located on terrain feature": (["Place", "Location"], ["Place", "Location"]),
    "located in or next to body of water": (["Place", "Location"], ["BodyOfWater"]),
    "mouth of the watercourse": (["BodyOfWater"], ["BodyOfWater", "Location"]),
    "basin country": (["BodyOfWater"], ["Place"]),
    "narrative location": (["Work"], ["Place", "Location"]),
    "location": (None, ["Place", "Location"]),
    "location of formation": (["Organization", "Conflict"], ["Place", "Location"]),
    "residence": (["Person"], ["Place", "Location"]),
    "work location": (["Person"], ["Place", "Location", "Organization"]),
    "genre": (["Work"], ["Genre"]),
    "series": (["Work", "Product"], ["Work", "Concept"]),
    "original language of work": (["Work"], ["Language"]),
    "original network": (["Work"], ["Organization"]),
    "platform": (["Work", "Product"], ["Product", "Concept"]),
    "country of origin": (["Work", "Product"], ["Place"]),
    "characters": (["Work"], ["Person", "Concept"]),
    "present in work": (["Person", "Place", "Organization", "Concept"], ["Work"]),
    "notable work": (["Person"], ["Work"]),
    "influenced by": (["Person", "Work", "Concept"], ["Person", "Work", "Concept"]),
    "follows": (
        ["Person", "Work", "Product", "Position"],
        ["Person", "Work", "Product", "Position"],
    ),
    "followed by": (
        ["Person", "Work", "Product", "Position"],
        ["Person", "Work", "Product", "Position"],
    ),
    "replaces": (["Person", "Position", "Product"], ["Person", "Position", "Product"]),
    "replaced by": (
        ["Person", "Position", "Product"],
        ["Person", "Position", "Product"],
    ),
    "separated from": (None, None),
    "part of": (None, None),
    "has part": (None, None),
    "subclass of": (["Class", "Concept"], ["Class", "Concept"]),
    "parent taxon": (["Taxon"], ["Taxon"]),
    "religion": (["Person", "Place", "Organization"], ["Religion"]),
    "ethnic group": (["Person", "Place"], ["EthnicGroup"]),
    "languages spoken, written or signed": (["Place", "Person"], ["Language"]),
    "award received": (["Person", "Organization", "Work"], ["Award"]),
    "legislative body": (["Place", "AdministrativeTerritory"], ["Organization"]),
    "military branch": (["Person", "Organization"], ["Organization"]),
    "unemployment rate": (["Place"], ["Concept"]),
    "conflict": (["Person", "Organization", "Place"], ["Conflict"]),
    "participant": (["Conflict", "Event"], ["Person", "Organization", "Place"]),
    "participant of": (["Person", "Organization", "Place"], ["Conflict", "Event"]),
    "territory claimed by": (["Place", "AdministrativeTerritory"], ["Place"]),
    "applies to jurisdiction": (
        ["LegalDocument"],
        ["Place", "AdministrativeTerritory"],
    ),
    "product or material produced": (["Organization"], ["Product"]),
    "date of birth": (["Person"], ["Time"]),
    "date of death": (["Person"], ["Time"]),
    "inception": (["Organization", "Place", "Work", "Product"], ["Time"]),
    "dissolved, abolished or demolished": (
        ["Organization", "Place", "Location"],
        ["Time"],
    ),
    "publication date": (["Work"], ["Time"]),
    "start time": (None, ["Time"]),
    "end time": (None, ["Time"]),
    "point in time": (None, ["Time"]),
}
